apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""
data:
  Corefile: |
    {% for host, ip in loopbacks.items() %}
    {{ host }}:53 {
        hosts {
            {{ ip }} {{ host }}
        }
    }
    {% endfor %}

    .:53 {
        errors
        health
        ready

        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }

        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }

        prometheus :9153
        forward . 8.8.8.8 8.8.4.4
        cache 30
        loop
        reload
        loadbalance
        import /etc/coredns/custom/*.override
    }
    import /etc/coredns/custom/*.server
