apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-pat
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: SecretStore
  target:
    name: github-pat
    creationPolicy: Owner
  data:
    - secretKey: credentials
      remoteRef:
        key: /github/pat
