#!/bin/sh
# Auto-generated by coily lockdown. Do not edit; regenerate with
#   coily lockdown --apply --replace
#
# PreToolUse Bash hook for Claude Code Desktop, where the built-in
# permissions.deny matcher is silently bypassed (verified 2026-04-23 on
# v2.1.119). On the CLI the built-in matcher is the primary gate; this
# hook is defense-in-depth there. On Desktop this hook is the only gate.
#
# Reads tool-input JSON on stdin, extracts tool_input.command, splits on
# common shell separators, strips leading "env VAR=val" tokens, then
# tests the leading token of each segment against the deny prefixes
# below. Exits 2 with a stderr message on hit.

set -u

INPUT=$(cat)
# Pull tool_input.command via a single-line sed. JSON parsing in pure sh
# is fragile; this matches Claude Code's well-formed input. Backslash-
# escapes in the original command are not unescaped here - the leading-
# token compare is robust to that as long as the binary name itself does
# not contain escapes (it never does in practice).
CMD=$(printf '%s' "$INPUT" | sed -n 's/.*"command"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
if [ -z "$CMD" ]; then
  exit 0
fi

# Split CMD into segments at shell separators. A segment is the leading
# command of a pipeline / boolean / sequence / command substitution.
SEGMENTS=$(printf '%s\n' "$CMD" | awk '
{
  s = $0
  gsub(/\$\(/, "\n", s)
  gsub(/\)/,   "\n", s)
  gsub(/\|\|/, "\n", s)
  gsub(/&&/,   "\n", s)
  gsub(/[|;&]/, "\n", s)
  print s
}')

check_segment() {
  seg=$1
  # Strip leading whitespace.
  seg=$(printf '%s' "$seg" | sed -E 's/^[[:space:]]+//')
  [ -z "$seg" ] && return 0
  # Strip leading "env VAR=val ..." tokens (env on its own is denied
  # anyway, but env-prefixed invocations of an allowed binary should be
  # tested against the underlying binary).
  while printf '%s' "$seg" | grep -qE '^env( +[A-Za-z_][A-Za-z0-9_]*=[^ ]+)+( +|$)'; do
    seg=$(printf '%s' "$seg" | sed -E 's/^env( +[A-Za-z_][A-Za-z0-9_]*=[^ ]+)+( +|$)//')
  done
  case "$seg" in
    "aws"|"aws "*) printf 'lockdown: blocked by deny rule: aws\n' >&2; exit 2 ;;
    "bash"|"bash "*) printf 'lockdown: blocked by deny rule: bash\n' >&2; exit 2 ;;
    "bun"|"bun "*) printf 'lockdown: blocked by deny rule: bun\n' >&2; exit 2 ;;
    "cargo run"|"cargo run "*) printf 'lockdown: blocked by deny rule: cargo run\n' >&2; exit 2 ;;
    "cmd"|"cmd "*) printf 'lockdown: blocked by deny rule: cmd\n' >&2; exit 2 ;;
    "cmd.exe"|"cmd.exe "*) printf 'lockdown: blocked by deny rule: cmd.exe\n' >&2; exit 2 ;;
    "cscript"|"cscript "*) printf 'lockdown: blocked by deny rule: cscript\n' >&2; exit 2 ;;
    "cscript.exe"|"cscript.exe "*) printf 'lockdown: blocked by deny rule: cscript.exe\n' >&2; exit 2 ;;
    "dash"|"dash "*) printf 'lockdown: blocked by deny rule: dash\n' >&2; exit 2 ;;
    "deno"|"deno "*) printf 'lockdown: blocked by deny rule: deno\n' >&2; exit 2 ;;
    "docker"|"docker "*) printf 'lockdown: blocked by deny rule: docker\n' >&2; exit 2 ;;
    "env"|"env "*) printf 'lockdown: blocked by deny rule: env\n' >&2; exit 2 ;;
    "exec"|"exec "*) printf 'lockdown: blocked by deny rule: exec\n' >&2; exit 2 ;;
    "fish"|"fish "*) printf 'lockdown: blocked by deny rule: fish\n' >&2; exit 2 ;;
    "gcloud"|"gcloud "*) printf 'lockdown: blocked by deny rule: gcloud\n' >&2; exit 2 ;;
    "gh"|"gh "*) printf 'lockdown: blocked by deny rule: gh\n' >&2; exit 2 ;;
    "git clean -fd"|"git clean -fd "*) printf 'lockdown: blocked by deny rule: git clean -fd\n' >&2; exit 2 ;;
    "git push --force"|"git push --force "*) printf 'lockdown: blocked by deny rule: git push --force\n' >&2; exit 2 ;;
    "git push -f"|"git push -f "*) printf 'lockdown: blocked by deny rule: git push -f\n' >&2; exit 2 ;;
    "git reset --hard"|"git reset --hard "*) printf 'lockdown: blocked by deny rule: git reset --hard\n' >&2; exit 2 ;;
    "go run"|"go run "*) printf 'lockdown: blocked by deny rule: go run\n' >&2; exit 2 ;;
    "helm"|"helm "*) printf 'lockdown: blocked by deny rule: helm\n' >&2; exit 2 ;;
    "invoke"|"invoke "*) printf 'lockdown: blocked by deny rule: invoke\n' >&2; exit 2 ;;
    "just"|"just "*) printf 'lockdown: blocked by deny rule: just\n' >&2; exit 2 ;;
    "ksh"|"ksh "*) printf 'lockdown: blocked by deny rule: ksh\n' >&2; exit 2 ;;
    "kubectl annotate"|"kubectl annotate "*) printf 'lockdown: blocked by deny rule: kubectl annotate\n' >&2; exit 2 ;;
    "kubectl apply"|"kubectl apply "*) printf 'lockdown: blocked by deny rule: kubectl apply\n' >&2; exit 2 ;;
    "kubectl attach"|"kubectl attach "*) printf 'lockdown: blocked by deny rule: kubectl attach\n' >&2; exit 2 ;;
    "kubectl autoscale"|"kubectl autoscale "*) printf 'lockdown: blocked by deny rule: kubectl autoscale\n' >&2; exit 2 ;;
    "kubectl cordon"|"kubectl cordon "*) printf 'lockdown: blocked by deny rule: kubectl cordon\n' >&2; exit 2 ;;
    "kubectl cp"|"kubectl cp "*) printf 'lockdown: blocked by deny rule: kubectl cp\n' >&2; exit 2 ;;
    "kubectl create"|"kubectl create "*) printf 'lockdown: blocked by deny rule: kubectl create\n' >&2; exit 2 ;;
    "kubectl debug"|"kubectl debug "*) printf 'lockdown: blocked by deny rule: kubectl debug\n' >&2; exit 2 ;;
    "kubectl delete"|"kubectl delete "*) printf 'lockdown: blocked by deny rule: kubectl delete\n' >&2; exit 2 ;;
    "kubectl drain"|"kubectl drain "*) printf 'lockdown: blocked by deny rule: kubectl drain\n' >&2; exit 2 ;;
    "kubectl edit"|"kubectl edit "*) printf 'lockdown: blocked by deny rule: kubectl edit\n' >&2; exit 2 ;;
    "kubectl exec"|"kubectl exec "*) printf 'lockdown: blocked by deny rule: kubectl exec\n' >&2; exit 2 ;;
    "kubectl expose"|"kubectl expose "*) printf 'lockdown: blocked by deny rule: kubectl expose\n' >&2; exit 2 ;;
    "kubectl kustomize"|"kubectl kustomize "*) printf 'lockdown: blocked by deny rule: kubectl kustomize\n' >&2; exit 2 ;;
    "kubectl label"|"kubectl label "*) printf 'lockdown: blocked by deny rule: kubectl label\n' >&2; exit 2 ;;
    "kubectl patch"|"kubectl patch "*) printf 'lockdown: blocked by deny rule: kubectl patch\n' >&2; exit 2 ;;
    "kubectl port-forward"|"kubectl port-forward "*) printf 'lockdown: blocked by deny rule: kubectl port-forward\n' >&2; exit 2 ;;
    "kubectl proxy"|"kubectl proxy "*) printf 'lockdown: blocked by deny rule: kubectl proxy\n' >&2; exit 2 ;;
    "kubectl replace"|"kubectl replace "*) printf 'lockdown: blocked by deny rule: kubectl replace\n' >&2; exit 2 ;;
    "kubectl rollout pause"|"kubectl rollout pause "*) printf 'lockdown: blocked by deny rule: kubectl rollout pause\n' >&2; exit 2 ;;
    "kubectl rollout restart"|"kubectl rollout restart "*) printf 'lockdown: blocked by deny rule: kubectl rollout restart\n' >&2; exit 2 ;;
    "kubectl rollout resume"|"kubectl rollout resume "*) printf 'lockdown: blocked by deny rule: kubectl rollout resume\n' >&2; exit 2 ;;
    "kubectl rollout undo"|"kubectl rollout undo "*) printf 'lockdown: blocked by deny rule: kubectl rollout undo\n' >&2; exit 2 ;;
    "kubectl run"|"kubectl run "*) printf 'lockdown: blocked by deny rule: kubectl run\n' >&2; exit 2 ;;
    "kubectl scale"|"kubectl scale "*) printf 'lockdown: blocked by deny rule: kubectl scale\n' >&2; exit 2 ;;
    "kubectl set"|"kubectl set "*) printf 'lockdown: blocked by deny rule: kubectl set\n' >&2; exit 2 ;;
    "kubectl taint"|"kubectl taint "*) printf 'lockdown: blocked by deny rule: kubectl taint\n' >&2; exit 2 ;;
    "kubectl uncordon"|"kubectl uncordon "*) printf 'lockdown: blocked by deny rule: kubectl uncordon\n' >&2; exit 2 ;;
    "make"|"make "*) printf 'lockdown: blocked by deny rule: make\n' >&2; exit 2 ;;
    "mshta"|"mshta "*) printf 'lockdown: blocked by deny rule: mshta\n' >&2; exit 2 ;;
    "mshta.exe"|"mshta.exe "*) printf 'lockdown: blocked by deny rule: mshta.exe\n' >&2; exit 2 ;;
    "node"|"node "*) printf 'lockdown: blocked by deny rule: node\n' >&2; exit 2 ;;
    "nox"|"nox "*) printf 'lockdown: blocked by deny rule: nox\n' >&2; exit 2 ;;
    "npm"|"npm "*) printf 'lockdown: blocked by deny rule: npm\n' >&2; exit 2 ;;
    "osascript"|"osascript "*) printf 'lockdown: blocked by deny rule: osascript\n' >&2; exit 2 ;;
    "perl"|"perl "*) printf 'lockdown: blocked by deny rule: perl\n' >&2; exit 2 ;;
    "pnpm"|"pnpm "*) printf 'lockdown: blocked by deny rule: pnpm\n' >&2; exit 2 ;;
    "powershell"|"powershell "*) printf 'lockdown: blocked by deny rule: powershell\n' >&2; exit 2 ;;
    "powershell.exe"|"powershell.exe "*) printf 'lockdown: blocked by deny rule: powershell.exe\n' >&2; exit 2 ;;
    "pwsh"|"pwsh "*) printf 'lockdown: blocked by deny rule: pwsh\n' >&2; exit 2 ;;
    "pwsh.exe"|"pwsh.exe "*) printf 'lockdown: blocked by deny rule: pwsh.exe\n' >&2; exit 2 ;;
    "python"|"python "*) printf 'lockdown: blocked by deny rule: python\n' >&2; exit 2 ;;
    "python3"|"python3 "*) printf 'lockdown: blocked by deny rule: python3\n' >&2; exit 2 ;;
    "regsvr32"|"regsvr32 "*) printf 'lockdown: blocked by deny rule: regsvr32\n' >&2; exit 2 ;;
    "regsvr32.exe"|"regsvr32.exe "*) printf 'lockdown: blocked by deny rule: regsvr32.exe\n' >&2; exit 2 ;;
    "rsync"|"rsync "*) printf 'lockdown: blocked by deny rule: rsync\n' >&2; exit 2 ;;
    "ruby"|"ruby "*) printf 'lockdown: blocked by deny rule: ruby\n' >&2; exit 2 ;;
    "rundll32"|"rundll32 "*) printf 'lockdown: blocked by deny rule: rundll32\n' >&2; exit 2 ;;
    "rundll32.exe"|"rundll32.exe "*) printf 'lockdown: blocked by deny rule: rundll32.exe\n' >&2; exit 2 ;;
    "scp"|"scp "*) printf 'lockdown: blocked by deny rule: scp\n' >&2; exit 2 ;;
    "sh"|"sh "*) printf 'lockdown: blocked by deny rule: sh\n' >&2; exit 2 ;;
    "ssh"|"ssh "*) printf 'lockdown: blocked by deny rule: ssh\n' >&2; exit 2 ;;
    "sshfs"|"sshfs "*) printf 'lockdown: blocked by deny rule: sshfs\n' >&2; exit 2 ;;
    "tailscale"|"tailscale "*) printf 'lockdown: blocked by deny rule: tailscale\n' >&2; exit 2 ;;
    "task"|"task "*) printf 'lockdown: blocked by deny rule: task\n' >&2; exit 2 ;;
    "terraform"|"terraform "*) printf 'lockdown: blocked by deny rule: terraform\n' >&2; exit 2 ;;
    "tflint"|"tflint "*) printf 'lockdown: blocked by deny rule: tflint\n' >&2; exit 2 ;;
    "tfsec"|"tfsec "*) printf 'lockdown: blocked by deny rule: tfsec\n' >&2; exit 2 ;;
    "tox"|"tox "*) printf 'lockdown: blocked by deny rule: tox\n' >&2; exit 2 ;;
    "wscript"|"wscript "*) printf 'lockdown: blocked by deny rule: wscript\n' >&2; exit 2 ;;
    "wscript.exe"|"wscript.exe "*) printf 'lockdown: blocked by deny rule: wscript.exe\n' >&2; exit 2 ;;
    "xargs"|"xargs "*) printf 'lockdown: blocked by deny rule: xargs\n' >&2; exit 2 ;;
    "yarn"|"yarn "*) printf 'lockdown: blocked by deny rule: yarn\n' >&2; exit 2 ;;
    "zsh"|"zsh "*) printf 'lockdown: blocked by deny rule: zsh\n' >&2; exit 2 ;;
  esac
}

# Iterate segments. heredoc is a single-process loop so an exit inside
# check_segment terminates the whole script.
while IFS= read -r seg; do
  check_segment "$seg"
done <<EOF
$SEGMENTS
EOF

exit 0
