apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama
  namespace: llama
  labels:
    app: llama
spec:
  selector:
    matchLabels:
      app: llama
  template:
    metadata:
      labels:
        app: llama
    spec:
      volumes:
        - name: models
          emptyDir: {}
      initContainers:
        - name: download-resource
          image: busybox
          command:
            [
              "wget",
              "-O",
              "/models/DeepSeek-V2-Lite-Chat-Q2_K.gguf",
              "https://huggingface.co/tensorblock/DeepSeek-V2-Lite-Chat-GGUF/resolve/main/DeepSeek-V2-Lite-Chat-Q2_K.gguf",
            ]
          volumeMounts:
            - name: models
              mountPath: /models
      imagePullSecrets:
        - name: docker-registry
      containers:
        - name: llama
          image: ghcr.io/ggml-org/llama.cpp:server
          resources:
            limits:
              cpu: 4000m
              memory: 4096Mi
          command:
            - -m
            - /models/DeepSeek-V2-Lite-Chat-Q2_K.gguf
            - --port
            - "8080"
            - --host
            - "0.0.0.0"
          volumeMounts:
            - name: models
              mountPath: /models
          ports:
            - containerPort: 8080
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: llama-service
  namespace: llama
spec:
  type: ClusterIP
  selector:
    app: llama
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
