apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama
  namespace: llama
  labels:
    app: llama
spec:
  selector:
    matchLabels:
      app: llama
  template:
    metadata:
      labels:
        app: llama
    spec:
      volumes:
        - name: models
          emptyDir: {}
      initContainers:
        - name: download-resource
          image: busybox
          command:
            [
              "wget",
              "-O",
              "/models/tinyllama-1.1b-chat-v1.0.Q6_K.gguf",
              "https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q6_K.gguf",
            ]
          volumeMounts:
            - name: models
              mountPath: /models
      imagePullSecrets:
        - name: docker-registry
      containers:
        - name: llama
          image: ghcr.io/ggml-org/llama.cpp:server
          resources:
            requests:
              cpu: 10
              memory: 5120Mi
            limits:
              cpu: 10
              memory: 5120Mi
          command:
            - /app/llama-server
            - -m
            - /models/tinyllama-1.1b-chat-v1.0.Q6_K.gguf
            - --port
            - "8080"
            - --host
            - "0.0.0.0"
          volumeMounts:
            - name: models
              mountPath: /models
          ports:
            - containerPort: 8080
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: llama-service
  namespace: llama
  annotations:
    tailscale.com/expose: "true"
spec:
  type: ClusterIP
  selector:
    app: llama
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
