#!/usr/bin/env python3
"""One-time bulk migration: land the managed AGENTS.md pointer block on canonical.

The generator, validator, and applier are authored in coilyco-flight-deck/agentic-os
(agentic-os#196). The `agents-pointer` pre-commit hook is the durable guard against
drift. This script is the one-time rollout that gets the block into each managed
repo's canonical Forgejo `main` in the first place - after it runs once, the hook
keeps every future commit honest and this script never needs to run again.

Per managed repo (coilyco-flight-deck/* and coilyco-bridge/*, AGENTS.md present,
block missing or drifted), in --execute mode:
  1. Skip unless the repo is on `main` with a clean tree (never inject into
     in-progress work).
  2. File a same-repo Forgejo issue (the commit-msg `closes-issue` hook requires a
     same-repo URL, and it has no bot bypass).
  3. Render and write the block via the agentic-os applier logic.
  4. Commit (`chore:`, closing that issue's URL) - all pre-commit hooks run.
  5. Push HEAD:main to the repo's Forgejo URL (never the GitHub mirror).

Default is a dry run: it reports the plan and writes nothing. Pass --execute to act.
Failures are per-repo and non-fatal: the run continues and reports them at the end.

Authored side of coilyco-flight-deck/infrastructure#269. Ongoing drift is the
`agents-pointer` ansible role's report and the pre-commit hook's job, not this.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

DEFAULT_AOS_ROOT = Path.home() / "projects" / "coilyco-flight-deck" / "agentic-os"
FORGEJO_HOST = "forgejo.coilysiren.me"
_ISSUE_URL_RE = re.compile(rf"https://{re.escape(FORGEJO_HOST)}/\S+/issues/\d+")

COMMIT_TITLE = "chore: render managed AGENTS.md workspace-pointer block"
ISSUE_TITLE = "chore: render managed AGENTS.md workspace-pointer block"
ISSUE_BODY = (
    "Replace the hand-written workspace-pointer line in AGENTS.md with the managed "
    "block generated by agentic-os (generate-agents-pointer). One-time rollout from "
    "coilyco-flight-deck/infrastructure#269; the agents-pointer pre-commit hook guards "
    "drift from here on."
)


# Populated by load_applier() from the checked-out agentic-os repo. Keyed handles
# keep the dynamic (post-sys.path) import in one place and off every call signature.
FN: dict = {}


def load_applier(aos_root: Path) -> None:
    """Import the agentic-os pointer logic from the checked-out aos repo into FN."""
    sys.path.insert(0, str(aos_root))
    try:
        # pylint: disable=import-outside-toplevel
        from agentic_os.config import iter_workspace_repos
        from agentic_os.generate_agents_pointer import (
            apply_to_text,
            detect_org_repo,
            is_managed,
        )
    except ModuleNotFoundError as exc:  # pragma: no cover
        sys.exit(
            f"cannot import agentic_os from {aos_root} ({exc}). "
            "Pass --aos-root to point at the agentic-os checkout."
        )
    FN.update(
        iter_repos=iter_workspace_repos,
        apply=apply_to_text,
        detect=detect_org_repo,
        managed=is_managed,
    )


def _git(repo: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-C", str(repo), *args], capture_output=True, text=True, check=False
    )


def _is_clean_on_main(repo: Path) -> tuple[bool, str]:
    branch = _git(repo, "symbolic-ref", "--short", "HEAD").stdout.strip()
    if branch != "main":
        return False, f"on '{branch}', not main"
    if _git(repo, "status", "--porcelain").stdout.strip():
        return False, "working tree dirty"
    return True, ""


def _file_issue(org: str, repo: str) -> str | None:
    """File a same-repo Forgejo issue, return its URL (or None on failure)."""
    body_path = Path(f"/tmp/agents-pointer-issue-{org}-{repo}.md")
    body_path.write_text(ISSUE_BODY)
    proc = subprocess.run(
        [
            "coily", "ops", "forgejo", "issue", "create",
            "--repo", f"{org}/{repo}",
            "--title", ISSUE_TITLE,
            "--body-file", str(body_path),
        ],
        capture_output=True, text=True, check=False,
    )
    m = _ISSUE_URL_RE.search(proc.stdout + proc.stderr)
    return m.group(0) if m else None


def migrate_repo(repo_dir: Path, org: str, repo: str, execute: bool) -> tuple[str, str]:
    """Return (action, detail) for one repo."""
    # pylint: disable=too-many-return-statements
    before = (repo_dir / "AGENTS.md").read_text()
    after = FN["apply"](before, org)
    if after is None:
        return "skip", "unmanaged"
    if after == before:
        return "ok", "already current"
    if not execute:
        return "would-migrate", org

    clean, why = _is_clean_on_main(repo_dir)
    if not clean:
        return "blocked", why

    issue_url = _file_issue(org, repo)
    if not issue_url:
        return "fail", "could not file Forgejo issue"

    (repo_dir / "AGENTS.md").write_text(after)
    _git(repo_dir, "add", "AGENTS.md")
    msg = f"{COMMIT_TITLE}\n\ncloses {issue_url}"
    commit = _git(repo_dir, "commit", "-m", msg)
    if commit.returncode != 0:
        return "fail", f"commit failed: {commit.stdout.strip()[-200:]} {commit.stderr.strip()[-200:]}"

    forgejo_url = f"https://{FORGEJO_HOST}/{org}/{repo}.git"
    push = _git(repo_dir, "push", forgejo_url, "HEAD:main")
    if push.returncode != 0:
        return "fail", f"pushed nothing: {push.stderr.strip()[-200:]}"
    return "migrated", f"{org} ({issue_url})"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    ap.add_argument("--execute", action="store_true", help="act for real (default: dry run)")
    ap.add_argument("--repo", help="migrate a single repo by name")
    ap.add_argument("--limit", type=int, help="cap the number of repos acted on")
    ap.add_argument("--aos-root", type=Path, default=DEFAULT_AOS_ROOT)
    args = ap.parse_args(argv)

    load_applier(args.aos_root)

    repos = []
    for repo_dir in FN["iter_repos"]():
        if args.repo and repo_dir.name != args.repo:
            continue
        org, repo = FN["detect"](repo_dir)
        agents = repo_dir / "AGENTS.md"
        if FN["managed"](org, repo) and agents.exists() and not agents.is_symlink():
            repos.append((repo_dir, org, repo))

    print(f"{'EXECUTE' if args.execute else 'DRY RUN'}: {len(repos)} managed repo(s) in scope\n")
    counts: dict[str, int] = {}
    acted = 0
    for repo_dir, org, repo in repos:
        if args.limit is not None and acted >= args.limit and args.execute:
            break
        action, detail = migrate_repo(repo_dir, org, repo, args.execute)
        counts[action] = counts.get(action, 0) + 1
        if action in ("migrated", "would-migrate", "blocked", "fail"):
            print(f"  {repo_dir.name:28} {action:14} {detail}")
            if action == "migrated":
                acted += 1

    print("\nSummary:", ", ".join(f"{k}={v}" for k, v in sorted(counts.items())))
    return 1 if counts.get("fail") else 0


if __name__ == "__main__":
    sys.exit(main())
