#!/usr/bin/env bash
# create-deploy-user.sh - provision the `deploy` CI service account on
# kai-server. Idempotent: re-run safely after a partial run or as a
# rebuild step. Each operation skips when the desired state already
# holds.
#
# Why this user exists:
#   - Per-repo CI workflows (coilysiren/repo-recall, coilysiren/galaxy-gen)
#     use tag:ci tailnet OIDC to ssh into kai-server and roll k3s
#     deployments. The destination user has to be a real Linux account
#     (Tailscale SSH refuses unknown users with "failed to look up local
#     user"). `deploy` separates CI auth from the human `kai` user.
#   - Locked password + bash shell: no interactive login is possible
#     (no password matches), but `tailscale ssh deploy@kai-server
#     "<cmd>"` works because tailnet membership is the auth boundary.
#   - NOPASSWD sudo for the k3s binary: lets `docker save | ssh deploy
#     'sudo k3s ctr images import -'` and `ssh deploy 'sudo k3s kubectl
#     set image ...'` complete without an interactive password prompt.
#     Scope is the whole k3s binary rather than per-argv because strict
#     argv matching has burned the rig before (coilysiren/coily#244).
#     The actual gate is tailnet OIDC + the tag:ci ACL, not sudoers.
#
# Prereqs:
#   - Run as `kai` (or any sudo-capable user) on kai-server.
#   - k3s already installed (binary at /usr/local/bin/k3s).
#   - Tailscale SSH ACL grants tag:ci → user:deploy. Managed in
#     terraform/tailscale-oidc/ or the global tailnet policy.
#
# Cross-link: coilysiren/infrastructure#191 (the finding that motivated
# this script).

set -euo pipefail

USER_NAME="deploy"
SUDOERS_PATH="/etc/sudoers.d/${USER_NAME}"
K3S_BINARY="/usr/local/bin/k3s"

if [[ "$(id -u)" -eq 0 ]]; then
  echo "error: do not run as root; the script invokes sudo per-step so the audit log captures who ran it" >&2
  exit 1
fi

if ! command -v sudo >/dev/null; then
  echo "error: sudo not on PATH" >&2
  exit 1
fi

echo "==> user: ${USER_NAME}"
if id "${USER_NAME}" >/dev/null 2>&1; then
  echo "    already exists ($(id "${USER_NAME}"))"
else
  sudo useradd \
    --system \
    --user-group \
    --create-home \
    --shell /bin/bash \
    --comment "CI deploy account, tag:ci tailnet ssh only" \
    "${USER_NAME}"
  echo "    created: $(id "${USER_NAME}")"
fi

echo "==> password lock"
# `passwd -S` prints "USER L ..." when the password is already locked.
# Skip re-locking if the L status is already there - lets the script
# stay quiet on a re-run.
status="$(sudo passwd -S "${USER_NAME}" | awk '{print $2}')"
case "${status}" in
  L|LK)
    echo "    already locked"
    ;;
  *)
    sudo passwd -l "${USER_NAME}"
    echo "    locked"
    ;;
esac

echo "==> sudoers: ${SUDOERS_PATH}"
# Heredoc into a tempfile, visudo-check it, then atomic install.
# Avoids leaving a half-written /etc/sudoers.d/deploy if anything
# above this line errors out.
tmp="$(mktemp)"
trap 'rm -f "${tmp}"' EXIT
cat >"${tmp}" <<EOF
# CI deploy account: tailnet-authed via tag:ci -> deploy@kai-server.
# Scope: container-image import + deployment rolls via k3s.
# Anything else still requires the absent password and falls through.
# Generated by infrastructure/scripts/create-deploy-user.sh.
${USER_NAME} ALL=(root) NOPASSWD: ${K3S_BINARY}
EOF
sudo visudo -cf "${tmp}" >/dev/null
sudo install -m 0440 -o root -g root "${tmp}" "${SUDOERS_PATH}"
echo "    installed (mode 0440, root:root)"

echo
echo "==> verify"
echo "--- id"
id "${USER_NAME}"
echo "--- passwd -S"
sudo passwd -S "${USER_NAME}"
echo "--- visudo -cf ${SUDOERS_PATH}"
sudo visudo -cf "${SUDOERS_PATH}"
echo "--- sudo -lU ${USER_NAME}"
sudo -lU "${USER_NAME}" | grep -E "^(User|.*NOPASSWD)" || true
echo
echo "done. `tailscale ssh ${USER_NAME}@kai-server` should now work from any tag:ci node."
