#!/usr/bin/env bash
# Provision the `deploy` CI account on kai-server: locked-password user with
# NOPASSWD sudo for k3s, gated by tag:ci tailnet OIDC. Idempotent (infrastructure#191).

set -euo pipefail

USER_NAME="deploy"
SUDOERS_PATH="/etc/sudoers.d/${USER_NAME}"
K3S_BINARY="/usr/local/bin/k3s"

if [[ "$(id -u)" -eq 0 ]]; then
  echo "error: do not run as root; the script invokes sudo per-step so the audit log captures who ran it" >&2
  exit 1
fi

if ! command -v sudo >/dev/null; then
  echo "error: sudo not on PATH" >&2
  exit 1
fi

echo "==> user: ${USER_NAME}"
if id "${USER_NAME}" >/dev/null 2>&1; then
  echo "    already exists ($(id "${USER_NAME}"))"
else
  sudo useradd \
    --system \
    --user-group \
    --create-home \
    --shell /bin/bash \
    --comment "CI deploy account, tag:ci tailnet ssh only" \
    "${USER_NAME}"
  echo "    created: $(id "${USER_NAME}")"
fi

echo "==> password lock"
# `passwd -S` prints "USER L ..." when already locked; skip re-locking on the L
# status so re-runs stay quiet.
status="$(sudo passwd -S "${USER_NAME}" | awk '{print $2}')"
case "${status}" in
  L|LK)
    echo "    already locked"
    ;;
  *)
    sudo passwd -l "${USER_NAME}"
    echo "    locked"
    ;;
esac

echo "==> sudoers: ${SUDOERS_PATH}"
# Heredoc into a tempfile, visudo-check, then atomic install, so a mid-write
# error never leaves a half-written /etc/sudoers.d/deploy.
tmp="$(mktemp)"
trap 'rm -f "${tmp}"' EXIT
cat >"${tmp}" <<EOF
# CI deploy account (tag:ci -> deploy@kai-server): scoped to k3s for image
# import + deploy rolls. Generated by scripts/create-deploy-user.sh.
${USER_NAME} ALL=(root) NOPASSWD: ${K3S_BINARY}
EOF
sudo visudo -cf "${tmp}" >/dev/null
sudo install -m 0440 -o root -g root "${tmp}" "${SUDOERS_PATH}"
echo "    installed (mode 0440, root:root)"

echo
echo "==> verify"
echo "--- id"
id "${USER_NAME}"
echo "--- passwd -S"
sudo passwd -S "${USER_NAME}"
echo "--- visudo -cf ${SUDOERS_PATH}"
sudo visudo -cf "${SUDOERS_PATH}"
echo "--- sudo -lU ${USER_NAME}"
sudo -lU "${USER_NAME}" | grep -E "^(User|.*NOPASSWD)" || true
echo
echo "done. `tailscale ssh ${USER_NAME}@kai-server` should now work from any tag:ci node."
