#!/usr/bin/env python3
"""generate-caddy-shortcuts.py - regenerate caddy/sites/*.caddy from
sibling repos' coily.yaml (or legacy config.yml) `tailnet.shortcut`
declarations.

Walks every coilysiren/* repo on Forgejo, fetches each default
branch's coily.yaml (falling back to config.yml during the
agentic-os-kai#439 rename), and writes one Caddy site snippet per
declared shortcut. Stale files (snippets whose owning repo no longer
declares a shortcut, or was removed) are deleted.

Runs in Forgejo Actions (.forgejo/workflows/caddy-shortcuts.yml) and
locally for debugging. Stdlib only - no PyYAML dependency. YAML parsing
defers to `yq` (already present in the deploy toolchain).

Manual reload after a regen lands on kai-server:

    cd ~/projects/coilysiren/infrastructure && git pull
    sudo caddy reload --config /etc/caddy/Caddyfile
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path

FORGEJO_URL = os.environ.get("FORGEJO_URL", "https://forgejo.coilysiren.me").rstrip("/")
FORGEJO_TOKEN = os.environ.get("FORGEJO_TOKEN", "")

# Upstream that handles every Host header that already routes through
# Traefik. Pulled from docs/k3s-deploy-notes.md §1: Traefik LoadBalancer
# listens on 192.168.0.194:80 in namespace kube-system.
TRAEFIK_UPSTREAM = "192.168.0.194:80"

# Shortcut tokens must match this so a malformed entry can't smuggle Caddy
# syntax into the generated file.
SHORTCUT_RE = re.compile(r"^[a-z0-9][a-z0-9-]*[a-z0-9]$")

SNIPPET_HEADER = "# generated by scripts/generate-caddy-shortcuts.py from {repo}/coily.yaml. do not edit.\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--owner", default="coilysiren")
    ap.add_argument(
        "--sites-dir",
        default=str(Path(__file__).resolve().parent.parent / "caddy" / "sites"),
        help="output directory for generated snippets",
    )
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="print what would change, do not touch disk",
    )
    args = ap.parse_args()

    sites_dir = Path(args.sites_dir)
    sites_dir.mkdir(parents=True, exist_ok=True)

    repos = list_repos(args.owner)
    print(f"scanning {len(repos)} repos under {args.owner}/", file=sys.stderr)

    desired: dict[str, str] = {}  # shortcut -> snippet contents
    for repo in repos:
        cfg = fetch_config(args.owner, repo)
        if cfg is None:
            continue
        shortcut, dns_name = extract_shortcut(cfg)
        if not shortcut:
            continue
        if not SHORTCUT_RE.match(shortcut):
            print(f"{repo}: shortcut {shortcut!r} fails validation, skipping", file=sys.stderr)
            continue
        if not dns_name:
            print(f"{repo}: tailnet.shortcut set but dns-name missing, skipping", file=sys.stderr)
            continue
        if shortcut in desired:
            print(f"{repo}: shortcut {shortcut!r} collides with earlier repo, skipping", file=sys.stderr)
            continue
        desired[shortcut] = render_snippet(repo=f"{args.owner}/{repo}", shortcut=shortcut, dns_name=dns_name)

    changes = reconcile(sites_dir, desired, dry_run=args.dry_run)
    print(f"shortcuts: {len(desired)} desired / {changes} changes", file=sys.stderr)
    return 0


def list_repos(owner: str) -> list[str]:
    """Return repo names under owner on Forgejo (excluding forks and archived).
    Paginates over the search API."""
    names: list[str] = []
    page = 1
    while True:
        url = (
            f"{FORGEJO_URL}/api/v1/repos/search"
            f"?owner={owner}&limit=50&page={page}&archived=false"
        )
        payload = forgejo_get_json(url)
        if not payload:
            break
        data = payload.get("data") or []
        if not data:
            break
        for r in data:
            if r.get("fork"):
                continue
            names.append(r["name"])
        if len(data) < 50:
            break
        page += 1
    return names


def fetch_config(owner: str, repo: str) -> dict | None:
    """Fetch coily.yaml (or legacy config.yml) from a repo's default branch
    on Forgejo and parse it via yq. Returns None if neither file is present.

    Transition: coilysiren/agentic-os-kai#439 renames per-repo deploy configs from
    `config.yml` to `coily.yaml`. Try the new name first, fall back to legacy.
    """
    payload: dict | None = None
    for filename in ("coily.yaml", "config.yml"):
        url = f"{FORGEJO_URL}/api/v1/repos/{owner}/{repo}/contents/{filename}"
        result = forgejo_get_json(url)
        # Forgejo's contents endpoint returns an object for files and a
        # list for directories. Only the file shape is useful here.
        if isinstance(result, dict) and result.get("type") == "file":
            payload = result
            break
    if payload is None:
        return None
    try:
        body = base64.b64decode(payload["content"]).decode("utf-8")
    except (KeyError, ValueError):
        return None
    try:
        as_json = sh(["yq", "-o", "json", "."], stdin=body)
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None
    try:
        return json.loads(as_json)
    except json.JSONDecodeError:
        return None


def forgejo_get_json(url: str):
    """GET a Forgejo API URL and return the parsed JSON (dict or list).
    Returns None on 404 or any error; this keeps the caller's
    "missing = skip" semantics."""
    req = urllib.request.Request(url)
    if FORGEJO_TOKEN:
        req.add_header("Authorization", f"token {FORGEJO_TOKEN}")
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except (urllib.error.HTTPError, urllib.error.URLError, json.JSONDecodeError):
        return None


def extract_shortcut(cfg: dict) -> tuple[str | None, str | None]:
    tailnet = cfg.get("tailnet")
    if not isinstance(tailnet, dict):
        return None, None
    shortcut = tailnet.get("shortcut")
    if not isinstance(shortcut, str):
        return None, None
    dns_name = cfg.get("dns-name")
    return shortcut, dns_name if isinstance(dns_name, str) else None


def render_snippet(repo: str, shortcut: str, dns_name: str) -> str:
    header = SNIPPET_HEADER.format(repo=repo)
    return (
        header
        + f"handle_path /{shortcut}/* {{\n"
        + f"    reverse_proxy {TRAEFIK_UPSTREAM} {{\n"
        + f"        header_up Host {dns_name}\n"
        + "    }\n"
        + "}\n"
    )


def reconcile(sites_dir: Path, desired: dict[str, str], dry_run: bool) -> int:
    """Make sites_dir match desired exactly. Returns the count of
    file-level changes (write + delete)."""
    changes = 0
    existing = {p.stem: p for p in sites_dir.glob("*.caddy")}

    # Refuse mass-deletes when there's something to compare against. A
    # transient Forgejo API failure (or an auth issue masking private
    # repos) can make every desired shortcut disappear, which would
    # otherwise blow away the whole sites dir on a green run.
    to_delete = [s for s in existing if s not in desired]
    if existing and len(to_delete) > max(2, len(existing) // 2):
        print(
            f"refusing to delete {len(to_delete)} of {len(existing)} shortcuts "
            f"in one run (desired={len(desired)}); likely upstream enumeration "
            "failed. re-run with --dry-run to inspect.",
            file=sys.stderr,
        )
        sys.exit(2)

    for shortcut, body in desired.items():
        target = sites_dir / f"{shortcut}.caddy"
        if target.exists() and target.read_text(encoding="utf-8") == body:
            continue
        print(f"write caddy/sites/{shortcut}.caddy", file=sys.stderr)
        if not dry_run:
            target.write_text(body, encoding="utf-8")
        changes += 1

    for shortcut, path in existing.items():
        if shortcut in desired:
            continue
        print(f"delete caddy/sites/{path.name}", file=sys.stderr)
        if not dry_run:
            path.unlink()
        changes += 1

    return changes


def sh(argv: list[str], stdin: str | None = None) -> str:
    """Run argv, return stdout as str. Raises on non-zero exit."""
    proc = subprocess.run(
        argv,
        input=stdin,
        capture_output=True,
        text=True,
        check=True,
    )
    return proc.stdout


if __name__ == "__main__":
    sys.exit(main())
