#!/usr/bin/env python3
"""generate-aws-inventory.py - emit aws-inventory.yaml, an auto-generated
listing of every AWS resource Kai uses.

Kai's AWS footprint is small and strictly non-overlapping: SSM Parameter
Store params, S3 buckets, and Route53 hosted zones. None of it is
Terraform-managed (the terraform/ dirs cover Grafana, KMS, and Tailscale
only), so this is a query-and-emit script rather than `terraform output`.

Public-safety stance: this file lists what exists, never the contents.
SSM parameter names, bucket names, and DNS record names are meaningful
identifiers and ship as literals - the same names already appear in
checked-in docs. Parameter values, S3 object listings, and Route53
record values are deliberately omitted. A record value would leak the
home public IP, an SSM value is by definition a secret. An inventory
needs neither.

Runs locally via `coily exec aws-inventory` (Makefile target
aws-inventory). Credentials resolve through the standard boto3 chain,
same as `coily ops aws`. See coilysiren/infrastructure#227.
"""

from __future__ import annotations

import datetime
import sys
from pathlib import Path

import boto3

REGION = "us-east-1"
OUTPUT = Path(__file__).resolve().parent.parent / "aws-inventory.yaml"

HEADER = """\
# Auto-generated by scripts/generate-aws-inventory.py. Do not edit by hand.
# Refresh: coily exec aws-inventory
#
# This is an inventory of what exists, not a dump of contents. Resource
# values (SSM parameter values, Route53 record values, S3 objects) are
# deliberately omitted - see the script docstring and #227.
"""


def collect_ssm(client) -> list[dict]:
    """Every SSM parameter, name + type + last-modified. No values."""
    out: list[dict] = []
    paginator = client.get_paginator("describe_parameters")
    for page in paginator.paginate():
        for param in page["Parameters"]:
            out.append(
                {
                    "name": param["Name"],
                    "type": param.get("Type", "unknown"),
                    "last_modified": _iso(param.get("LastModifiedDate")),
                }
            )
    out.sort(key=lambda p: p["name"])
    return out


def collect_s3(client) -> list[dict]:
    """Every S3 bucket, name + region + creation date."""
    out: list[dict] = []
    for bucket in client.list_buckets().get("Buckets", []):
        name = bucket["Name"]
        try:
            loc = client.get_bucket_location(Bucket=name)["LocationConstraint"]
        except client.exceptions.ClientError:
            loc = None
        out.append(
            {
                "name": name,
                # us-east-1 reports as null per the S3 API quirk.
                "region": loc or "us-east-1",
                "created": _iso(bucket.get("CreationDate")),
            }
        )
    out.sort(key=lambda b: b["name"])
    return out


def collect_route53(client) -> list[dict]:
    """Every hosted zone with its record names + types. No record values."""
    out: list[dict] = []
    zone_paginator = client.get_paginator("list_hosted_zones")
    for zone_page in zone_paginator.paginate():
        for zone in zone_page["HostedZones"]:
            zone_id = zone["Id"].split("/")[-1]
            records: list[dict] = []
            rec_paginator = client.get_paginator("list_resource_record_sets")
            for rec_page in rec_paginator.paginate(HostedZoneId=zone_id):
                for rec in rec_page["ResourceRecordSets"]:
                    records.append({"name": rec["Name"], "type": rec["Type"]})
            records.sort(key=lambda r: (r["name"], r["type"]))
            out.append(
                {
                    "zone": zone["Name"],
                    "private": zone.get("Config", {}).get("PrivateZone", False),
                    "record_count": len(records),
                    "records": records,
                }
            )
    out.sort(key=lambda z: z["zone"])
    return out


def _iso(value) -> str | None:
    if isinstance(value, datetime.datetime):
        return value.astimezone(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return None


def _emit_yaml(inventory: dict) -> str:
    """Hand-rolled YAML for a fixed, flat-ish schema. No PyYAML dependency,
    matching the stdlib-only bias of the sibling generator scripts."""
    lines: list[str] = [HEADER.rstrip("\n"), ""]
    lines.append(f"generated_at: \"{inventory['generated_at']}\"")
    lines.append(f"region: {inventory['region']}")
    lines.append("")

    lines.append("ssm_parameters:")
    for param in inventory["ssm_parameters"]:
        lines.append(f"  - name: {_scalar(param['name'])}")
        lines.append(f"    type: {param['type']}")
        lines.append(f"    last_modified: {_scalar(param['last_modified'])}")
    if not inventory["ssm_parameters"]:
        lines[-1] = "ssm_parameters: []"
    lines.append("")

    lines.append("s3_buckets:")
    for bucket in inventory["s3_buckets"]:
        lines.append(f"  - name: {_scalar(bucket['name'])}")
        lines.append(f"    region: {bucket['region']}")
        lines.append(f"    created: {_scalar(bucket['created'])}")
    if not inventory["s3_buckets"]:
        lines[-1] = "s3_buckets: []"
    lines.append("")

    lines.append("route53:")
    for zone in inventory["route53"]:
        lines.append(f"  - zone: {_scalar(zone['zone'])}")
        lines.append(f"    private: {str(zone['private']).lower()}")
        lines.append(f"    record_count: {zone['record_count']}")
        lines.append("    records:")
        for rec in zone["records"]:
            lines.append(f"      - name: {_scalar(rec['name'])}")
            lines.append(f"        type: {rec['type']}")
        if not zone["records"]:
            lines[-1] = "    records: []"
    if not inventory["route53"]:
        lines[-1] = "route53: []"

    return "\n".join(lines) + "\n"


def _scalar(value) -> str:
    """Quote a scalar so leading slashes, colons, or null render safely."""
    if value is None:
        return "null"
    return '"' + str(value).replace('"', '\\"') + '"'


def main() -> int:
    session = boto3.session.Session(region_name=REGION)
    inventory = {
        "generated_at": datetime.datetime.now(datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        ),
        "region": REGION,
        "ssm_parameters": collect_ssm(session.client("ssm")),
        "s3_buckets": collect_s3(session.client("s3")),
        # Route53 is a global service; the region on the client is ignored.
        "route53": collect_route53(session.client("route53")),
    }
    OUTPUT.write_text(_emit_yaml(inventory))
    print(
        f"wrote {OUTPUT.name}: "
        f"{len(inventory['ssm_parameters'])} SSM params, "
        f"{len(inventory['s3_buckets'])} S3 buckets, "
        f"{len(inventory['route53'])} Route53 zones"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
